### ISSUE TITLE
Add Link to description

### ISSUE THREAD

**Issue by storopoli** [jaoleal/zola-blog#2]
I am missing a link in the repo's metadata:
<img width="404" alt="image" src="https://github.com/jaoleal/zola-blog/assets/43353831/ca31584c-c628-4427-8cbd-82e239541ae6">

If you go to this gear icon:
<img width="335" alt="image" src="https://github.com/jaoleal/zola-blog/assets/43353831/662acfff-c901-40b1-adc8-53390cc06461">

then click on `Use your GitHub Pages website`:
<img width="641" alt="image" src="https://github.com/jaoleal/zola-blog/assets/43353831/6d41d0ed-b5d9-41d7-b88b-63293e3b6768">

**Comment by jaoleal** [comment]
Done!
